import 'server-only';

import type { CanvasInsertionPayload, GenerateInput } from '../canvas/contracts';
import { uploadGeneratedAssetToSupabase } from '../supabase/storage-server';

const GEMINI_API_BASE = 'https://generativelanguage.googleapis.com/v1beta';
const GEMINI_IMAGE_MODEL = 'gemini-3.1-flash-image-preview';
const GEMINI_VEO_MODEL = 'veo-3.1-generate-preview';

type GeminiImageResponse = {
  candidates?: Array<{
    content?: {
      parts?: Array<{
        text?: string;
        inlineData?: {
          mimeType?: string;
          data?: string;
        };
      }>;
    };
  }>;
};

type VeoOperation = {
  name?: string;
  done?: boolean;
  response?: {
    generateVideoResponse?: {
      generatedSamples?: Array<{
        video?: {
          uri?: string;
        };
      }>;
    };
  };
};

function getGeminiApiKey() {
  const apiKey = process.env.GEMINI_API_KEY;

  if (!apiKey) {
    throw new Error('Missing GEMINI_API_KEY');
  }

  return apiKey;
}

export function isGeminiConfigured() {
  return Boolean(process.env.GEMINI_API_KEY);
}

function createGenerationPayload(input: {
  type: 'image' | 'video';
  prompt: string;
  title: string;
  subtitle: string;
  label: string;
  meta: string;
  previewUrl: string;
}): CanvasInsertionPayload {
  return {
    items: [
      {
        key: 'generated-result',
        data: {
          kind: 'generation',
          badge: 'Generated Result',
          title: input.title,
          subtitle: input.subtitle,
          accent: 'from-fuchsia-100 via-white to-rose-50',
          status: 'done',
          generationType: input.type,
          generationProvider: input.type === 'image' ? 'nanobanana' : 'veo',
          aspectRatio: '16:9',
          prompt: input.prompt,
          hideAssetMeta: true,
          assetItems: [
            {
              id: 'generated-asset',
              label: input.label,
              type: input.type,
              meta: input.meta,
              previewUrl: input.previewUrl,
            },
          ],
        },
      },
    ],
  };
}

async function generateImagePayload(prompt: string) {
  const apiKey = getGeminiApiKey();
  const response = await fetch(
    `${GEMINI_API_BASE}/models/${GEMINI_IMAGE_MODEL}:generateContent`,
    {
      method: 'POST',
      headers: {
        'x-goog-api-key': apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        contents: [
          {
            parts: [{ text: prompt }],
          },
        ],
        generationConfig: {
          responseModalities: ['TEXT', 'IMAGE'],
          imageConfig: {
            aspectRatio: '16:9',
          },
        },
      }),
    },
  );

  if (!response.ok) {
    throw new Error(`Gemini image request failed: ${response.status} ${await response.text()}`);
  }

  const json = (await response.json()) as GeminiImageResponse;
  const imagePart = json.candidates?.[0]?.content?.parts?.find(
    (part) => part.inlineData?.data,
  );
  const imageData = imagePart?.inlineData?.data;
  const mimeType = imagePart?.inlineData?.mimeType ?? 'image/png';

  if (!imageData) {
    throw new Error('Gemini image generation returned no image data');
  }

  const bytes = Uint8Array.from(Buffer.from(imageData, 'base64'));
  const uploaded = await uploadGeneratedAssetToSupabase({
    bytes,
    mimeType,
    extension: mimeType.includes('jpeg') ? 'jpg' : 'png',
    prefix: 'gemini-image',
  });

  return createGenerationPayload({
    type: 'image',
    prompt,
    title: 'Nano Banana image concept',
    subtitle: 'Gemini image generation output',
    label: 'nanobanana-generated-image.png',
    meta: 'Generated by Gemini image model and stored in Supabase',
    previewUrl: uploaded.publicUrl,
  });
}

async function startVideoGeneration(prompt: string) {
  const apiKey = getGeminiApiKey();
  const response = await fetch(
    `${GEMINI_API_BASE}/models/${GEMINI_VEO_MODEL}:predictLongRunning`,
    {
      method: 'POST',
      headers: {
        'x-goog-api-key': apiKey,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        instances: [{ prompt }],
        parameters: {
          aspectRatio: '16:9',
        },
      }),
    },
  );

  if (!response.ok) {
    throw new Error(`Veo request failed: ${response.status} ${await response.text()}`);
  }

  return (await response.json()) as VeoOperation;
}

async function pollVideoOperation(operationName: string) {
  const apiKey = getGeminiApiKey();
  let attempts = 0;

  while (attempts < 60) {
    const response = await fetch(`${GEMINI_API_BASE}/${operationName}`, {
      headers: {
        'x-goog-api-key': apiKey,
      },
    });

    if (!response.ok) {
      throw new Error(`Veo polling failed: ${response.status} ${await response.text()}`);
    }

    const operation = (await response.json()) as VeoOperation;

    if (operation.done) {
      return operation;
    }

    attempts += 1;
    await new Promise((resolve) => setTimeout(resolve, 10000));
  }

  throw new Error('Timed out waiting for Veo video generation');
}

async function generateVideoPayload(prompt: string) {
  const operation = await startVideoGeneration(prompt);
  const operationName = operation.name;

  if (!operationName) {
    throw new Error('Veo returned no operation name');
  }

  const completed = await pollVideoOperation(operationName);
  const videoUri =
    completed.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri;

  if (!videoUri) {
    throw new Error('Veo returned no generated video URI');
  }

  const downloadResponse = await fetch(videoUri, {
    headers: {
      'x-goog-api-key': getGeminiApiKey(),
    },
  });

  if (!downloadResponse.ok) {
    throw new Error(`Failed to download generated video: ${downloadResponse.status}`);
  }

  const bytes = new Uint8Array(await downloadResponse.arrayBuffer());
  const uploaded = await uploadGeneratedAssetToSupabase({
    bytes,
    mimeType: 'video/mp4',
    extension: 'mp4',
    prefix: 'veo-video',
  });

  return createGenerationPayload({
    type: 'video',
    prompt,
    title: 'Veo video concept',
    subtitle: 'Gemini video generation output',
    label: 'veo-generated-video.mp4',
    meta: 'Generated by Veo 3.1 and stored in Supabase',
    previewUrl: uploaded.publicUrl,
  });
}

export async function generateCanvasPayloadWithGemini(input: GenerateInput) {
  if (input.type === 'image') {
    return generateImagePayload(input.prompt);
  }

  if (input.type === 'video') {
    return generateVideoPayload(input.prompt);
  }

  throw new Error('Gemini provider is currently only wired for image and video generation');
}
