import 'server-only';

import { uploadGeneratedAssetToSupabase } from '../supabase/storage-server';
import type { CanvasInsertionPayload } from '../canvas/contracts';

const HERA_API_BASE = 'https://api.hera.video/v1';

type HeraCreateResponse = {
  video_id: string;
  project_url: string;
};

type HeraPollResponse = {
  video_id: string;
  status: 'in-progress' | 'success' | 'failed';
  outputs: Array<{
    status: 'in-progress' | 'success' | 'failed';
    file_url?: string;
    error?: string;
  }>;
};

function getApiKey(): string {
  const key = process.env.HERA_API_KEY;
  if (!key) throw new Error('Missing HERA_API_KEY');
  return key;
}

export function isHeraConfigured(): boolean {
  return Boolean(process.env.HERA_API_KEY);
}

async function startGeneration(prompt: string): Promise<string> {
  const apiKey = getApiKey();

  console.log('[hera] → POST /videos');
  const res = await fetch(`${HERA_API_BASE}/videos`, {
    method: 'POST',
    headers: {
      'x-api-key': apiKey,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      prompt,
      outputs: [{ format: 'mp4', aspect_ratio: '16:9', fps: '30', resolution: '720p' }],
    }),
  });

  console.log(`[hera] ← ${res.status}`);
  if (!res.ok) {
    const body = await res.text();
    console.error('[hera] create error:', body);
    throw new Error(`Hera request failed: ${res.status} ${body}`);
  }

  const json = (await res.json()) as HeraCreateResponse;
  console.log(`[hera] video_id: ${json.video_id}`);
  return json.video_id;
}

async function pollUntilDone(videoId: string): Promise<string> {
  const apiKey = getApiKey();

  for (let attempt = 0; attempt < 60; attempt++) {
    await new Promise((r) => setTimeout(r, 5_000));
    console.log(`[hera] poll ${attempt + 1}/60 — ${videoId}`);

    const res = await fetch(`${HERA_API_BASE}/videos/${videoId}`, {
      headers: { 'x-api-key': apiKey },
    });
    if (!res.ok) throw new Error(`Hera poll failed: ${res.status}`);

    const data = (await res.json()) as HeraPollResponse;
    console.log(`[hera] status: ${data.status}`);

    if (data.status === 'success') {
      const fileUrl = data.outputs?.[0]?.file_url;
      if (!fileUrl) throw new Error('Hera returned no file_url');
      return fileUrl;
    }

    if (data.status === 'failed') {
      throw new Error(`Hera generation failed: ${data.outputs?.[0]?.error ?? 'unknown error'}`);
    }
  }

  throw new Error('Timed out waiting for Hera video generation');
}

export async function generateHeraAnimationPayload(prompt: string): Promise<CanvasInsertionPayload> {
  const videoId = await startGeneration(prompt);
  const fileUrl = await pollUntilDone(videoId);

  console.log('[hera] Downloading video…');
  const dlRes = await fetch(fileUrl);
  if (!dlRes.ok) throw new Error(`Failed to download Hera video: ${dlRes.status}`);

  const bytes = new Uint8Array(await dlRes.arrayBuffer());
  console.log('[hera] Uploading to Supabase storage…');
  const uploaded = await uploadGeneratedAssetToSupabase({
    bytes,
    mimeType: 'video/mp4',
    extension: 'mp4',
    prefix: 'hera-animation',
  });
  console.log('[hera] Done:', uploaded.publicUrl);

  return {
    items: [
      {
        key: 'generated-result',
        data: {
          kind: 'generation',
          badge: 'Generated Result',
          title: 'Hera animation',
          subtitle: 'Motion graphics by Hera',
          accent: 'from-violet-100 via-white to-purple-50',
          status: 'done',
          generationType: 'video',
          generationProvider: 'hera',
          aspectRatio: '16:9',
          prompt,
          hideAssetMeta: true,
          assetItems: [
            {
              id: 'generated-asset',
              label: 'hera-animation.mp4',
              type: 'video',
              meta: 'Generated by Hera · stored in Supabase',
              previewUrl: uploaded.publicUrl,
            },
          ],
        },
      },
    ],
  };
}
